baseUrl = "https://newsa.gent"
languageCode = "en-us"
title = "NewsAgent"
theme = "anubis"
paginate = 5
googleAnalytics = "G-12345"
enableRobotsTXT = true

[menu]

[[menu.main]]
identifier = "posts"
name = "Posts"
title = "Posts"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "categories"
name = "Categories"
title = "Categories"
url = "/categories/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
title = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
identifier = "archive"
name = "Archive"
title = "Archive"
url = "/posts/"
weight = 5

[taxonomies]
category = "categories"
tag = "tags"

[params]
author = "Detlev Vandaele"
email = "detvdl@pm.me"
avatar = "/images/me.png"
description = "NewsAgent"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "light-without-switcher"
readMore = true
readNextPosts = 5
disableSummary = false
copyCodeButton = true
rssAsSocialIcon = true
customCSS = ["css/custom.css"]

  [[params.social]]
  id = "github"
  name = "detvdl"

  [[params.social]]
  id = "linkedin"
  name = "detlev-vandaele-2ba935172"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'lovelace'
    tabWidth = 4
